//
//  LoginWorker.swift
//  testCleanSwift
//
//  Created by Durk-jae Yun on 2019/12/01.
//  Copyright (c) 2019 Durk-jae Yun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
  func doSomeWork()
  {
  }
}
