[package]
name = "rust-cross-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rust-cross = { path = "../rust-cross" }
wasm-bindgen = "0.2.48"